### ISSUE TITLE
extras field doesn't seem to be honored in "setup.py test"

### ISSUE THREAD

**Issue by tszumowski** [pyscaffold/pyscaffold#228] opened 2019-02-21 17:57 UTC
## Description of your problem

This may be a misunderstanding of the `setup.cfg` parameters. If I build the demo example with `putup my_little_project` and add an entry in `setup.cfg`'s `extras_require` section, that "extra" **always** gets pulled in when I run `python setup.py test`

I tried setting `extras = False` in `setup.cfg`, for example:
```python
...
[test]
# py.test options when running `python setup.py test`
extras = False
```
(Note: the above starts off as `extras = True`.

I tested this by adding the following entry:
```python
...
[options.extras_require]
tf = tensorflow

# Add here test requirements (semicolon/line-separated)
...
```

Is this expected behavior?
If so, how do I keep `setup.py test` from pulling in extras? I don't want them all for unit tests, and I have an example below of non-pyscaffold setup.cfg that doesn't pull in extras by default.

Thank you.

**Please provide the full traceback.**
When I run the above `setup.cfg`, regardless of the `extras =` assignment, It always pulls in the `extras_require` package, in this example, `tensorflow`.

```python
$ python setup.py test
running test
Searching for tensorflow
Reading https://pypi.org/simple/tensorflow/
Downloading https://files.pythonhosted.org/packages/e1/9d/a963891122c1a674568aaea04263067c3c4f853e9efadd4c3af3d87240ab/tensorflow-1.13.0rc2-cp36-cp36m-macosx_10_11_x86_64.whl#sha256=0555528eb1108c716669748e085fbf77270b9d23415271a2c8e5bdca76c6dde6
Best match: tensorflow 1.13.0rc2
Processing tensorflow-1.13.0rc2-cp36-cp36m-macosx_10_11_x86_64.whl
Installing tensorflow-1.13.0rc2-cp36-cp36m-macosx_10_11_x86_64.whl to /Users/user/workspace/my_little_project/.eggs
```

**Please provide any additional information below.**
See the attached  file for the exact `setup.cfg` used:

[setup.cfg.pyscaffold.txt](https://github.com/pyscaffold/pyscaffold/files/2890454/setup.cfg.pyscaffold.txt)

This is an example setup.cfg **without** `pyscaffold` that does work. As in, when I run `python setup.py test` with this config, it does not pull in all `extras_require`:

[setup.cfg.noscaffold.working.txt](https://github.com/pyscaffold/pyscaffold/files/2890459/setup.cfg.noscaffold.working.txt)

## Versions and main components

* PyScaffold Version: 3.1
* Python Version: 3.6.7
* Operating system: macOS
* How did you install PyScaffold: pip

**Comment by FlorianWilhelm** [comment] 2019-02-22 15:27
@tszumowski Thanks for letting me know. What happens if you run it directly with `py.test`? Do the extra.requires get pulled in? And what do you mean without `pyscaffold`? So you set the folders all up by yourself?

**Comment by FlorianWilhelm** [comment] 2019-02-22 15:50
@tszumowski Okay, I think I solved it. You have to uncomment `extras = False`. Setting it to false doesn't work because pytest runner reads it as string `'False'` which evaluates to `True`. That's not a bug in PyScaffold but in [pytest-runner](https://github.com/pytest-dev/pytest-runner). I would appreciate if you inform the author about this. When it is fixed I will also update it within PyScaffold.

**Comment by tszumowski** [comment] 2019-02-22 16:39
@FlorianWilhelm Thank you for looking into. If I comment with `#extras = False` in the `setup.cfg.pyscaffold.txt` file above, it seems to error immediately stating "no module named pytest". This is the output:

```
$ python setup.py test
running test
running egg_info
writing src/my_little_project.egg-info/PKG-INFO
writing dependency_links to src/my_little_project.egg-info/dependency_links.txt
writing requirements to src/my_little_project.egg-info/requires.txt
writing top-level names to src/my_little_project.egg-info/top_level.txt
writing manifest file 'src/my_little_project.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    setup(use_pyscaffold=True)
  File "/Users/szumowskit1/.pyenv/versions/my_little_project_venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/szumowskit1/.pyenv/versions/3.6.7/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/szumowskit1/.pyenv/versions/3.6.7/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/szumowskit1/.pyenv/versions/3.6.7/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/szumowskit1/workspace/my_little_project/.eggs/PyScaffold-3.1-py3.6.egg/pyscaffold/contrib/ptr.py", line 176, in run
    return self.run_tests()
  File "/Users/szumowskit1/workspace/my_little_project/.eggs/PyScaffold-3.1-py3.6.egg/pyscaffold/contrib/ptr.py", line 187, in run_tests
    result_code = __import__('pytest').main()
ModuleNotFoundError: No module named 'pytest'
```

**Comment by FlorianWilhelm** [comment] 2019-02-22 16:57
Have you installed pytest? If you don't let it install it automatically, you must install pytest beforehand manually.

**Comment by tszumowski** [comment] 2019-02-22 18:23
@FlorianWilhelm that fixed it. Whoops! 
But that brings up a question. Until this bug is fixed, if one doesn't want to install all the extras, they have to install pytest before running a `setup.py` command, which seems counterintuitive. The alternative is to uncomment the `test_requires` section, but that's mentioned as discouraged in the docs. Guess until the bug is addressed in `pytest-runner`, not much to do other than those to options correct?

**Comment by tszumowski** [comment] 2019-02-22 18:30
Also, opened this ticket: 
https://github.com/pytest-dev/pytest-runner/issues/45

**Comment by FlorianWilhelm** [comment] 2019-02-23 17:16
@tszumowski Thanks for posting the bug. I think definitely one bug in `pytest-runner` is that it starts to install everything in the extra section.  Regarding the `#extras = False`. Might it be that you would have to write `#extras = false` (lower-case f)? That should also work instead of just commenting it.

**Comment by FlorianWilhelm** [comment] 2019-02-23 17:27
Lower-case and even 0 doesn't work either... I wonder though that this is not implemented within ` setuptools.command.test.Test` itself. So it seems `pytest-runner` would need to convert the proper strings to booleans itself. 

Nevertheless your problem will stay the same. Either you make sure that you have everything installed yourself before you run the test or pytest-runner will install all extras as it seems. At least that is how I understand the documented behaviour. I would recommend you anyway to switch to tox and define your test requirements inside`tox.ini`.

**Comment by FlorianWilhelm** [comment] 2019-02-23 17:29
Since this bug is not in PyScaffold I will close the issue. Feel free to reopen if you think otherwise.

**Closed by FlorianWilhelm** 2019-02-23 17:29 UTC
