### ISSUE TITLE
putup --django my project does not results with a functional template

### ISSUE THREAD

**Issue by aeweiwi** [pyscaffold/pyscaffold#264] opened 2020-01-18 23:57 UTC
First thanks for this great library, really impressive. I would like to point out that I tried using the pyscaffold library to setup a django template as follows:

```
putup --django my_project
cd my_project
python manage.py runserver
```

I have got the following error:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\programs\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\programs\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\programs\lib\site-packages\django\core\management\base.py", line 329, in run_from_argv
    connections.close_all()
  File "C:\programs\lib\site-packages\django\db\utils.py", line 220, in close_all
    for alias in self:
  File "C:\programs\lib\site-packages\django\db\utils.py", line 214, in __iter__
    return iter(self.databases)
  File "C:\programs\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\programs\lib\site-packages\django\db\utils.py", line 147, in databases
    self._databases = settings.DATABASES
  File "C:\programs\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "C:\programs\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\programs\lib\site-packages\django\conf\__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\programs\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_project'

```

to solve this, I went in manage.py, and settings.py  and replaced all instances where 
the reference to:
`'my_project.***'`
to  
`'src.my_project.***'`

I am using 
PyScaffold 3.2.2

**Comment by FlorianWilhelm** [comment] 2020-01-19 10:03
Hi @aeweiwi, thanks for reporting this bug. 

@abravalheri: What do you think? Should this bug fixed in version 3.3 or as a separate Plugin for version 4.0?

**Comment by aeweiwi** [comment] 2020-01-19 14:05
Hi, 

I would like to join the forces. I will be happy to fix it

**Comment by FlorianWilhelm** [comment] 2020-01-19 17:34
Hi @aeweiwi, that would be great! Thanks for your help, we are looking for your PR.

**Comment by abravalheri** [comment] 2020-01-20 09:25
Thanks @aeweiwi for reporting and working on that. I haven't been using django with PyScaffold, so I don't know exactly how they interplay. It is good to have some feedback.

@FlorianWilhelm, one solution that solves both things at the same time I think, is to put the extracted pyscaffoldext-django (and cookiecutter) as dependencies for PyScaffold 3.3 (as a transitional measure). I think it would work. This way we are still back compatible in a semantic-versioning way (the interfaces would be the same), but we avoid working with 2 different code bases. For PyScaffold 4, we just make it an optional dependency.

**Comment by FlorianWilhelm** [comment] 2020-01-20 11:28
@abravalheri, okay, I think that would work. Good idea.

**Comment by aeweiwi** [comment] 2020-01-20 15:25
hi @abravalheri. I have looking at the code base. It would be nice to give me a hint where to start on it.

**Comment by abravalheri** [comment] 2020-01-20 15:54
@aeweiwi, if you think the problem the problem is can be solved by string replacement in the files, one way of doing that could be registering an additional action after the files are created in disk ([after `create_django_proj`](https://github.com/pyscaffold/pyscaffoldext-django/blob/master/src/pyscaffoldext/django/extension.py).

**Comment by abravalheri** [comment] 2020-01-21 15:49
> 
> 
> @abravalheri, okay, I think that would work. Good idea.

@FlorianWilhelm I am doing some tests regarding this idea.
If you try 
```bash
pip install \
  --ignore-installed --no-cache-dir pip \
  --index-url https://test.pypi.org/simple/ \
  --extra-index-url https://pypi.org/simple \
  pyscaffold==3.3a0.dev0
```
things seem to work fine and the `putup` API is completely preserved (so "semantic versioning" backward compatible).

The packages in [test.pypi.org](test.pypi.org) refer to the new branches in [pyscaffoldext-cookiecutter](https://github.com/pyscaffold/pyscaffoldext-cookiecutter/tree/provisional), [pyscaffoldext-django](https://github.com/pyscaffold/pyscaffoldext-django/tree/provisional) and [my fork of pyscaffold](https://github.com/abravalheri/pyscaffold/tree/temp-extensions).

For the extensions, I had to relax a little bit the requirements on the PyScaffold version.
For the main package, I had to manually install the dependencies before running `python setup.py dists`, otherwise the build breaks.

Do you think we should proceed with this idea and release these versions on the main [pypi.org](pypi.org)?

**Comment by aeweiwi** [comment] 2020-01-21 23:34
Hi @abravalheri . I am reading the code base and getting my self familiar with it, and with the way cookiecutter works. I was thinking of replacing the project name with a prefix src.xxx in the same action of ([after create_django_proj](https://github.com/pyscaffold/pyscaffoldext-django/blob/master/src/pyscaffoldext/django/extension.py))

However, It seems that adding a separate action would look better. Currently, trying to understand how these actions is being called right now.

**Comment by FlorianWilhelm** [comment] 2020-01-22 08:33
@abravalheri, thanks for trying this out so fast. For me it seems to work. The only thing was that I had to install django using conda first to make it work but I think that's the usual pip/conda-mixture hiccup. Thus, I think we can proceed like you suggested.

The only other thing is to change the line in `manage.py`, right?
```
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "test_project.settings")
```

**Comment by aeweiwi** [comment] 2020-01-22 09:39
@FlorianWilhelm 
The files that contains reference to the project name are 
`wsgi.py`, `manage.py`, and `settings.py`

I will PR the fix later, my approach is simple. Just replacing the occurrence of `test_project.` with `src.test_project`. It worked, but there should be a better way for doing that

**Comment by abravalheri** [comment] 2020-01-22 13:24
Thank you very much @aeweiwi. Please take your time, it is really nice to have the feedback of someone using the django extension.

Once you provide the PR that you are confident with, I will port the code to [pyscaffoldext-django](http://github.com/pyscaffold/pyscaffoldext-django).

Is there any check we can add in the tests to avoid this issue to passing undetected?

**Comment by aeweiwi** [comment] 2020-01-23 08:04
well the tests fails, have to look at it :(

**Comment by abravalheri** [comment] 2020-07-07 19:11
I was investigating a little bit more this issue based on the PR.
The reason why prefixing the module name with `src` works is because Django relies on the new-ish `__init__`-less namespace feature of modern python installations. So django thinks the actual package is `src.<package name>`, which is conceptually wrong and confusing...

It turns out it is quite trick to coerce django in using a `src`-layout... It simply does not provide those options out of the box.
In my quick investigation, to really make things seem properly configured, I had to do the following changes:

- add a `sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))` on top of `manage.py`
- add a `PROJECT_DIR = os.path.dirname(BASE_DIR)` on `settings.py`
- change the following on `setting.py`:
```diff
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
-       'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
+       'NAME': os.path.join(PROJECT_DIR, 'db.sqlite3'),
    }
}
```

Otherwise django would generate a sqlite file inside the `src` folder (which does not look very appropriate).
Still generating sqlite files in arbitrary places on the disk do not look a pretty option. I suppose if someone really wants to bundle a django website as package, it would be the best to have this configuration passed via environment variable.

@FlorianWilhelm, automating this things is doable (this is alternative 1)
Alternative 2 is to display a message after the installation instructing the user to manually change it.
Alternative 3 is to deprecate the django extension completely and write some documents on how to do the integration with PyScaffold...

In all alternatives, if the default templates for Django change, we have to revisit the extension/messages/docs...

**Comment by abravalheri** [comment] 2020-07-24 13:59
Things should work in `pyscaffoldex-django` by the time we release the official package.

**Closed by abravalheri** 2020-07-24 13:59 UTC
Labels: bug
